---

- name: Install packages needed for netsim
  become: true
  apt:
    name: xsltproc
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Create netsim device network
  shell: source {{ install.nso_dir }}/ncsrc && ncs-netsim create-network {{ install.extracted_xe_ned }} {{ install.xe_netsim_count }} xe
  args:
    executable: /bin/bash
  ignore_errors: true

- name: Add to netsim device network
  shell: source {{ install.nso_dir }}/ncsrc && ncs-netsim add-to-network {{ install.extracted_xr_ned }} {{ install.xr_netsim_count }} xr
  args:
    executable: /bin/bash
  ignore_errors: true

- name: Start netsim devices
  shell: source {{ install.nso_dir }}/ncsrc && ncs-netsim start
  args:
    executable: /bin/bash
  ignore_errors: true

- name: Create netsim list to add to NSO devices
  shell: source {{ install.nso_dir }}/ncsrc && ncs-netsim ncs-xml-init > devices.xml
  args:
    executable: /bin/bash
    creates: devices.xml
  ignore_errors: true

- name: Load devices into NSO
  shell: source {{ install.nso_dir }}/ncsrc && ncs_load -l -m devices.xml
  args:
    executable: /bin/bash
  ignore_errors: true

- include: action/sync-from.yml
