---

- name: Copy Packages to NSO Host
  copy:
    src: "{{ install.local_packages_dir }}/{{ item }}"
    dest: "{{ install.nso_dir }}/ncs-run/packages"
  loop:
    "{{ install.packages }}"

# - name: Compile Packages
#   make:
#     chdir: "{{ install.nso_dir }}/ncs-run/packages/{{ item }}/src"
#   environment:
#     NCS_DIR: "/home/{{ install.user }}/nso-{{ install.version }}"
#   loop:
#     "{{ install.packages }}"

# - include: action/packages-reload.yml
