---
# Local Host software location
local_binary_dir: ../binary
local_neds_dir: ../neds
local_packages_dir: ../packages
local_templates_dir: ../templates

# Remote Host
user: vagrant
nso_dir: $HOME/nso-5.6.1
temp_files_dir: /tmp

# Binary
version: 5.6.1
os : linux.x86_64

# NED Info for neds-install.yml
xr_ned: ncs-5.6.1-cisco-iosxr-7.36.3
extracted_xr_ned: cisco-iosxr-cli-7.36
xe_ned: ncs-5.6.1-cisco-ios-6.76.2
extracted_xe_ned: cisco-ios-cli-6.76

# NSO netsim
xe_netsim_count: 1
xr_netsim_count: 6
# netsim_hostname: pe

# Custom NSO Packages
packages:
  # - baseline
  # - bfd
  # - bgp
  # - dhcp
  # - dns
  # - evpn
  # - evpn_irb
  # - interconnect
  # - interface
  # - isis
  # - l2vpn
  # - logging
  # - loopback
  # - mpls
  # - ntp
  - olt_deploy
  # - segment_routing
  # - vrf
  # - baseline


# Custom NSO Static Templates
templates:
  - mdt

# V2 NED Install
ned_list:
  - ncs-5.6.1-cisco-ios-6.76.2.signed.bin
  - ncs-5.6.1-cisco-iosxr-7.36.3.signed.bin